#name: pr-ci-dummy.yml
#on:
#  pull_request:
#
#jobs:
#  bonjour:
#    name: Bonjour
#    runs-on:
#      group: aws-m8i-2xlarge-cache
#    steps:
#      - name: Just echo
#        run: |
#          echo "Bonjour, le monde!"
